# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Comment.create([
  { :user_id => 1, :post_id => 1, :body => "#rob rules!", :created_at => "2013-03-05 15:44:58", :updated_at => "2013-03-05 15:44:58" },
  { :user_id => 2, :post_id => 2, :body => "commenting on my own post", :created_at => "2013-03-05 16:46:36", :updated_at => "2013-03-05 16:46:36" },
  { :user_id => 2, :post_id => 1, :body => "#fred rules more!", :created_at => "2013-03-05 16:47:05", :updated_at => "2013-03-05 16:47:05" },
  { :user_id => 3, :post_id => 3, :body => "and twitter!", :created_at => "2013-03-05 16:47:51", :updated_at => "2013-03-05 16:47:51" },
  { :user_id => 4, :post_id => 3, :body => "idk i don't use twitter", :created_at => "2013-03-05 16:49:00", :updated_at => "2013-03-05 16:49:00" }
], :without_protection => true )



Follow.create([
  { :follower_id => 2, :followee_id => 1, :created_at => "2013-03-05 15:45:31", :updated_at => "2013-03-05 15:45:31" }
], :without_protection => true )



Friend.create([
  { :user1_id => nil, :user2_id => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Post.create([
  { :user_id => 1, :body => "#hashtags are my thang", :created_at => "2013-03-05 15:44:46", :updated_at => "2013-03-05 15:44:46" },
  { :user_id => 2, :body => "hey i'm fred #first", :created_at => "2013-03-05 16:45:40", :updated_at => "2013-03-05 16:45:40" },
  { :user_id => 3, :body => "can't wait until this includes fb support!", :created_at => "2013-03-05 16:47:39", :updated_at => "2013-03-05 16:47:39" }
], :without_protection => true )



Posttag.create([
  { :post_id => nil, :tag_id => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Tag.create([
  { :tagname => "hashtags", :created_at => "2013-03-05 15:44:46", :updated_at => "2013-03-05 15:44:46" },
  { :tagname => "first", :created_at => "2013-03-05 16:45:40", :updated_at => "2013-03-05 16:45:40" }
], :without_protection => true )



User.create([
  { :name => "rob", :username => "rob", :email => "rob", :password_digest => "$2a$10$JaKtur/W.so/bJsNy6UaaeVOP24G35JmmvR4xbHR1rZbXOw3RVLf.", :created_at => "2013-03-05 15:44:30", :updated_at => "2013-03-05 15:44:30" },
  { :name => "fred", :username => "fred", :email => "fred", :password_digest => "$2a$10$PqXFp2F8weNMOjKtV0YKoOdEWjDX9.CgY5942ULtij5Sy5.qprH0K", :created_at => "2013-03-05 15:45:17", :updated_at => "2013-03-05 15:45:17" },
  { :name => "jim", :username => "jim", :email => "jim", :password_digest => "$2a$10$P1VLxd1sgAbSCDLNoH/V0OlmB9hUHINJKDVTIORVgfD48IitmrO7C", :created_at => "2013-03-05 16:47:20", :updated_at => "2013-03-05 16:47:20" },
  { :name => "pete", :username => "pete", :email => "pete", :password_digest => "$2a$10$8tf5SD7t9d/4gfqTSXrJR..lBaEpHKKRA2KhYcXj9TupKBwQy2rJ.", :created_at => "2013-03-05 16:48:13", :updated_at => "2013-03-05 16:48:13" }
], :without_protection => true )


